# Generated by Django 3.1.5 on 2021-01-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UTMParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.CharField(max_length=10)),
                ('campaign_source', models.CharField(max_length=100)),
                ('campaign_medium', models.EmailField(max_length=100)),
                ('campaign_term', models.CharField(max_length=100)),
                ('campaign_content', models.CharField(max_length=100)),
                ('campaign_name', models.CharField(max_length=100)),
            ],
        ),
    ]
