# Generated by Django 3.1.5 on 2021-01-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210108_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='utmparameter',
            name='campaign_content',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='utmparameter',
            name='campaign_medium',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='utmparameter',
            name='campaign_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='utmparameter',
            name='campaign_source',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='utmparameter',
            name='campaign_term',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='utmparameter',
            name='website_url',
            field=models.CharField(max_length=256),
        ),
    ]
