# Generated by Django 3.1.5 on 2021-01-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210108_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='utmparameter',
            name='campaign_hashed_url',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='utmparameter',
            name='campaign_url',
            field=models.CharField(default=None, max_length=1024),
        ),
    ]
